make release script works for helm3 & helm3 charts

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -25,7 +25,7 @@ jobs:
       - name: Setup Helm
         uses: azure/setup-helm@v1
         with:
-          version: v2.16.1
+          version: v3.1.2
 
       - name: helm-check
         run: yarn helm-lint
@@ -60,10 +60,12 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         run: |
-          echo "Sync with existing charts repo in s3..."
-          mkdir -p chart-repo
-          aws s3 sync s3://magda-charts/ chart-repo
-          helm package ./deploy/${REPO_NAME} -d chart-repo --save=false
-          helm repo index chart-repo
-          echo "Releasing charts to s3..."
-          aws s3 sync chart-repo s3://magda-charts/ --acl public-read
+          cd deploy
+          mkdir -p sync_dir
+          mkdir -p index_dir
+          if ! aws s3 cp s3://magda-charts/index.yaml index_dir/index.yaml; then echo "failed to copy current repo index" && exit 1; fi
+          helm package -d sync_dir magda-function-template
+          helm repo index --merge "index_dir/index.yaml" sync_dir
+          mv -f sync_dir/index.yaml index_dir/index.yaml
+          aws s3 sync sync_dir s3://magda-charts/ --acl public-read
+          aws s3 cp index_dir/index.yaml s3://magda-charts/index.yaml --acl public-read
